export const CATEGORIES_ACTIONS_TYPES = {
    FETCH_CATEGORY_START: "categories/FETCH_CATEGORY_START",
    FETCH_CATEGORY_SUCCESS: "categories/FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_FAILED: "categories/FETCH_CATEGORY_FAILED",
};
